# -*- coding: utf-8 -*-
"""RF_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uf-2Il17If_553uhIj8BLaaGcPKLs3Sl

# Random Forest Regression
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

file_name = 'realistic_housing_data.xlsx'
df = pd.read_excel(file_name)

print(f"\n📊 Dataset Shape: {df.shape}")
print(f"Features: {df.columns.tolist()}")

print("\n📈 Dataset Info:")
print(df.info())

print("\n📋 First 5 rows:")
df.head()

print("\n📊 Statistical Summary:")
print(df.describe())

df.isnull().sum()

# Correlation heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation between Numerical Features")
plt.show()

# Split features and target
X = df.drop("price", axis=1)
y = df["price"]

categorical_features = X.select_dtypes(include=["object"]).columns
numerical_features = X.select_dtypes(include=["int64", "float64"]).columns

print(categorical_features)
print(numerical_features)

"""If column City = ['Delhi', 'Mumbai'], then after encoding:

id  city
1    delhi
2    Mumbai

id |City_Delhi | City_Mumbai
 1    1     |      0
 2    0     |      1

price = 10, 100, 601, 6000, 100000  --> 2.2, 4.3, -1.8, 1.9
"""

# Create ColumnTransformer for encoding
preprocessor = ColumnTransformer([
    ("onehot", OneHotEncoder(handle_unknown='ignore'), categorical_features),
    ("scale", StandardScaler(), numerical_features)
])

# Build the pipeline with RandomForestRegressor
pipeline = Pipeline([
    ("preprocess", preprocessor),
    ("model", RandomForestRegressor(random_state=42))
])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train the model
pipeline.fit(X_train, y_train)

# Predict on test data
y_pred = pipeline.predict(X_test)

# Evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("📊 Model Evaluation:")
print(f"Mean Absolute Error (MAE): ₹{mae:.2f}")
print(f"Root Mean Squared Error (RMSE): ₹{rmse:.2f}")
print(f"R² Score: {r2:.2f}")

# Actual vs Predicted plot
plt.figure(figsize=(8, 5))
sns.scatterplot(x=y_test, y=y_pred)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted House Prices")
plt.plot([y.min(), y.max()], [y.min(), y.max()], '--r')
plt.show()